# fly.toml app configuration file generated for nuki-discord-bot on 2023-04-28T11:49:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nuki-discord-bot"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = []
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
